### ISSUE TITLE
I wonder how can I use it

### ISSUE THREAD

**Issue by AlickH** [gt6796c/flowchart-tw5#1]
How can I install this plugin to my tiddlywiki? Thanks!

**Comment by cook** [comment]
I hava a same question as @SIDmao.

**Comment by cook** [comment]
I've found the install method by refer to [this answer](https://groups.google.com/forum/#!msg/tiddlywiki/7X5nZR5-w8M/qhnNgrjan58J):

1. Clone this repo to a local directory `flowchart-tw5`
2. Clone the tw5 repo to a local directory `TiddlyWiki5`
3. Move `flowchart-tw5` to `TiddlyWiki5/plugins`.
4. Cd to `TiddlyWiki5/editions/empty`, edit the JSON file `tiddlywiki.info`, add a string, `"flowchart-tw5"`, into the `plugins` list.
5. Open the terminal, cd to `TiddlyWiki5`, run the command `nodejs tiddlywiki.js editions/empty --server` and open the http://127.0.0.1:8080
6. Create a tiddle, add the content of `[[$:/plugins/gt6796c/flowchart-tw5]]` and save.
7. Drag the link above to your tw file which you want to install the plugin, refer to the [official doc about manually installing plugins](http://tiddlywiki.com/static/Manually%2520installing%2520a%2520plugin.html) for more details.

**Comment by gt6796c** [comment]
You can install by browsing to https://gt6796c.github.io/ and dragging the flowchart-tw5 link to your TiddlyWiki.

I've updated the readme to include this information.

**Comment by cook** [comment]
Wonderful.

**Comment by tbkwatkins** [comment]
Hi, is there any way to add this to a simple html tiddlywiki file held in a dropbox?
